#! /usr/bin/env zsh
# reloads yabai correctly
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# If no window on the current space is focused after a window is destroyed or
# minimized, or an application is hidden, focus the window under the cursor.
yabai -m signal --add event=window_destroyed \
  action="${functions[focus_under_cursor]}"
yabai -m signal --add event=window_minimized \
  action="${functions[focus_under_cursor]}"
yabai -m signal --add event=application_hidden \
  action="${functions[focus_under_cursor]}"

function focus_under_cursor {
  if yabai -m query --windows --space |
      jq -er 'map(select(.focused == 1)) | length == 0' >/dev/null; then
    yabai -m window --focus mouse 2>/dev/null || true
  fi
}

yabai -m config layout bsp

yabai -m config window_placement second_child

# Padding
# yabai -m config top_padding 4
# yabai -m config bottom_padding 4
# yabai -m config left_padding 4
# yabai -m config right_padding 4
# yabai -m config window_gap 4

# mouse settings
yabai -m mouse_follows_focus on
yabai -m mouse_modifier fn
yabai -m mouse_action1 move
yabai -m mouse_action2 resize
yabai -m mouse_drop_action swap


# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off 
yabai -m rule --add app="^JetBrains Toolbox$" manage=off 
yabai -m rule --add app="^AlDente$" manage=off 
yabai -m rule --add app="^Activity Monitor$" manage=off 

yabai -m rule --add title="^About This Mac$" manage=off

echo "yabai configuration loaded.."
